name: On PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instal Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v1

      - name: Install terraform-doocs
        run: |-
          mkdir -p ~/.local/bin
          curl -L "$(
            curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | \
            jq -r '.assets[] | select(.name | contains("linux-amd64.tar.gz")) | .browser_download_url')" |
          tar -C ~/.local/bin -xzf - terraform-docs

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
